### ISSUE TITLE
If Cloudflare is open then error

### ISSUE THREAD

**Issue by wangqiliang** [Arch1tect/Chatbox#21]
WebSocket connection to 'wss://wangqiliang.com/socket.io/?EIO=3&transport=websocket&sid=yw4Kb2mBvLer0fULAAAL' failed: Error during WebSocket handshake: Unexpected response code: 400

**Comment by kn007** [comment]
Hey, guy.

Maybe because websocket over Cloudflare is vulnerable to proxies in the middle (often transparent) operating at the layer breaking the connection.

I will check it later.

So, what plain(80, 443, or other) is your backend server to using the Cloudflare?

**Comment by kn007** [comment]
You need to upgrade code, it's like using the old one now.

**Comment by wangqiliang** [comment]
@kn007 it's port 443 that I use on the backend server.

**Comment by kn007** [comment]
Port 443 is ok. Maybe because websocket over Cloudflare is breaked.

**Comment by wangqiliang** [comment]
close #21
