### ISSUE TITLE
聊天盒顶部在特定情况变色

### ISSUE THREAD

**Issue by Arch1tect** [Arch1tect/Chatbox#31]
如果收到信息，但是用户不在页面，我们会让页面标签闪烁提醒。如果用户在，但是聊天盒最小化，是否考虑让聊天盒的灰色顶部变色或者闪烁呢？

**Comment by kn007** [comment]
我觉得也是，昨晚就想了该问题。这个或许可以添加进来。

**Comment by Arch1tect** [comment]
聊天盒顶部的现在的颜色可能不适合变色，也可以考虑震动

**Comment by Arch1tect** [comment]
我决定先关闭该issue，目前在tab顶部已经有文字提示。
如有需要，可以考虑开一个新issue讨论其他提醒方式如声音震动等。

**Comment by kn007** [comment]
@Arch1tect  收到，目前还有个问题 ,Admin message，发给多窗口时，一个已读，另外的不会已读。。
参考新消息提醒。

**Comment by Arch1tect** [comment]
Gotcha!
