### ISSUE TITLE
CSS Bug

### ISSUE THREAD

**Issue by wangqiliang** [Arch1tect/Chatbox#34]
当修改名字时，由于字是白的而文本框onclick时还是白的，所以就……
![where-is-my-name](https://ooo.0o0.ooo/2016/02/13/56beead8b704d.jpeg)

**Comment by wangqiliang** [comment]
仔细查看，与各网站css覆盖了client.css有关。
建议在某些特定属性上加上 @importent

**Comment by kn007** [comment]
确定为lifeislikeaboat.com主题原因，未考虑到CSS嵌套问题。
@wangqiliang 具体你可以尝试http://lifeislikeaboat.com:4321 ，应该就没问题，主线版本以此为准。
目前css考虑的是独立的，而非嵌套到博客。。所以可能移植到博客，需要自己改下css。。比如我就是定制的。。

@Arch1tect 后续这个或许我们该考虑一下，添加个非全局版css。

**Comment by Arch1tect** [comment]
@wangqiliang 
已解决！ 

@kn007 
好主意！
