### ISSUE TITLE
username can XSS and css maybe have something wrong

### ISSUE THREAD

**Issue by kn007** [Arch1tect/Chatbox#48]
![](http://ww3.sinaimg.cn/large/9160da2egw1f1213j359yj20af0npt9q.jpg)

**Comment by kn007** [comment]
also can test changename to `<script>javascript:alert('XSS')</script>`, it's work

**Comment by Arch1tect** [comment]
对的，尽快改。。

**Comment by kn007** [comment]
坑爹的手机，居然被XSS搞得发热假死了

**Comment by kn007** [comment]
Fix it in https://github.com/Arch1tect/Chatbox/commit/2e3f3915f4d182572e937cab70c86d7b16e0bd6f
