### ISSUE TITLE
Horizontal scroll bar overflow in Firefox

### ISSUE THREAD

**Issue by kn007** [Arch1tect/Chatbox#49]
![](http://ww3.sinaimg.cn/large/9160da2egw1f128sij8ucj209y0mc74w.jpg)

**Comment by Arch1tect** [comment]
奇怪，我在mac的44.0.2版火狐里看到和chrome完全一样，没有这些问题。。

**Comment by kn007** [comment]
公司是旧版FF，我回头更新试试

**Comment by kn007** [comment]
22.0的版本，可以自动更新到43.0，现在更新试试

**Comment by kn007** [comment]
43.0.1可以更新到44.0.2。。

43.0.1测试正常了。

**Comment by kn007** [comment]
44.0.2也正常。看来是因为低版本的一些功能性缺失导致的。
