### ISSUE TITLE
pdf very large error (3mb~4mb)

### ISSUE THREAD

**Issue by fabi0w** [Arch1tect/Chatbox#68]
I'm having problem sending pdf 3mb ~ 4MB to download! network failure!
I need compress the file? your code is sending base64 freely, would be this the problem?

**Comment by Arch1tect** [comment]
Hi, I've seen this, it doesn't have to do with pdf format but the size of file. Basically the user need to send heartbeat every minute or so, however while the user is sending file, he can't send heartbeat, therefore he's disconnected. This is all setup of Socket.io, you can try changing the default heartbeat time limit. That's what I remembered, you may find better solution posting this question to Socket.io repo...

**Comment by fabi0w** [comment]
I understood! I redid my code with file upload system.`Var formidable = require ( 'formidable')`. Thanks for your the answer!
